### ISSUE TITLE
Ripple app android

### ISSUE THREAD

**Issue by Commander-Crash** [spleenware/ripple#21]
I want to say this is great work and This is more of a modification than a issue. I have been using the Ripple messenger app for android for a few weeks and I notice that in the menu option you have Remove friend set up and Preferences. Not There is nothing wrong with having a menu However can you move the "Remove friend" option somewhere else. This is a issue because I do not have pencil fingers and I end up hitting that and will have to rescan the contact over and over again, and I can not scan a contact that im not next to. Perhaps you can add a long press option on the Contact list for removing contact. Thanks and keep up the grate work.

**Comment by spleenware** [comment]
Good point. Hadn't thought of that. Sure, I'll redesign how the contact/friend is removed.

**Comment by spleenware** [comment]
OK, I have published ver 1.6.1, which now pops up confirmation dialog when you select Remove Friend.

**Comment by Commander-Crash** [comment]
Thanks. That works.
