### ISSUE TITLE
ripple tactical on ttgo t3 v1.6 433mhz

### ISSUE THREAD

**Issue by nlantz79** [spleenware/ripple#27]
finally received the new boards and got everything installed/ setup. being a ham radio operator I opted for the 433 boards but notice they do not talk to one another when setup and codes are shared for ripple tactical. is  frequency configurable like it is with ripple messenger?

**Comment by spleenware** [comment]
I have just published ver 1.2.1 on Play, and you can now configure the frequency. It's in the device setup screen, where you enter ID/Name. So, you will have to do the initial pairing/selection again.
