### ISSUE TITLE
ripple tactical buzzer on ttgo t3 1.6

### ISSUE THREAD

**Issue by zyrorl** [spleenware/ripple#28]
According to the instructions on instructables the buzzer pin is supposed to be gpio11 , however this board does not expose 11, but does expose 13. yet when messages are received, i cannot get any sound despite having installed a piezo buzzer.

Is there any chance of making this configurable or modifiable somehow?

**Comment by spleenware** [comment]
Ah, since I wrote that article I have changed the buzzer behaviour. It is now tied to the same as the LED pin, which is 25 on the TTGO board. ie. whenever the green LED goes on, the buzzer also sounds.

**Comment by zyrorl** [comment]
thanks that fixed it for me!
