### ISSUE TITLE
Mailbox setup.

### ISSUE THREAD

**Issue by ghost** [spleenware/ripple#32]
So I ran into a issue setting up a repeater with mailbox support. all is well with the repeater functions However I am unable to set up mail boxes. The set of pictures shows the errors. I did set up mail boxes on the client side of the devices via ripple messenger app. And ripple commander I programed the ttgo/ Heltec device for repeater. What is not shown is the qr codes for node setup on ripple messenger.

One more note I did look at it in SDR play and it seems like the signal are 2 different modulations. One is more spread spectrum and the other is more burst or OOK like.

My settings are:
MHz 925
group Id:13
ID: 3(Repeater)

Hardware:

3 Devices
Chip Info:
 - Chip Family: ESP32
 - Chip Model: ESP32D0WDQ6 (revision 1)
 - Number of Cores: 2
 - Max CPU Frequency: 240MHz
 - Has Bluetooth: YES
 - Has Embedded Flash: NO
 - Has Factory-Calibrated ADC: YES
![Screenshot_20210227-164310](https://user-images.githubusercontent.com/32895249/109402801-75f67d00-791e-11eb-8f6d-a6c90b6c3a6b.png)
![Screenshot_20210227-164348](https://user-images.githubusercontent.com/32895249/109402802-768f1380-791e-11eb-8ad1-a940ce42cd72.png)
![Screenshot_20210227-164413](https://user-images.githubusercontent.com/32895249/109402803-768f1380-791e-11eb-9475-6ef110026f5f.png)
![Screenshot_20210227-164446](https://user-images.githubusercontent.com/32895249/109402804-768f1380-791e-11eb-9ebb-c29c6ebea9ac.png)
![Screenshot_20210227-164552](https://user-images.githubusercontent.com/32895249/109402805-7727aa00-791e-11eb-9d04-b7adcc19ffdc.png)
![Screenshot_20210227-164557](https://user-images.githubusercontent.com/32895249/109402807-7727aa00-791e-11eb-92a1-a94e20db355a.png)
![Screenshot_20210227-164756](https://user-images.githubusercontent.com/32895249/109402808-77c04080-791e-11eb-8741-4615aa0cb6ef.png)

**Comment by spleenware** [comment]
When the RSSI shows 'Timed Out' then the repeater currently can't be reached.
I can see in the later screenshots that the RSSI is returning a value, so looks like the repeater is reachable in those instances. But, the value is VERY low (-157). Is the antenna connected properly?
Also, the 'Create mailbox' operation sometimes needs multiple attempts before you get the 'OK' response

**Comment by Commander-Crash** [comment]
It only shows -157 when i reset the usb back to the OTG cable. It will not display RSSI unless i reseat it. I tested the repeater and it seems to work however SDRPlay shows diffrent modulations when i try and send a msg with the commander app.

**Comment by Commander-Crash** [comment]
I notice ripple command will not send messages but ripple messenger will without issue. Is the Command app able to send messages to clients? or is not compatible? Thanks for the reply.

**Comment by spleenware** [comment]
Yes, Commander can also send messages. Have you scanned in the QR code of the other client into Commander? And, also you need to scan the QR code for the 'Home' node in the other client's app. 
(or you can use the special 'Exchange' chat room)

**Comment by spleenware** [comment]
Also, when using a custom LoRa frequency, the various sensor/repeater/tracker nodes you configure (with the 'Program' button) will get the frequency setting sent to them, so those should be automatic. HOWEVER, if you change the frequency (for the Group) you then have to do the 'Program' steps again.

Also, any Messenger of QWERTY pager devices must also setup the same frequency manually.

**Comment by Commander-Crash** [comment]
Sry my account got hacked and I forgot that I had this posted. This is still a no go. I have tried many different ttgo boards with same results. Can you recommend a board that this will work on?

**Comment by Commander-Crash** [comment]
Can you closed this for i can not. I don't want to double post
