### ISSUE TITLE
Error TimeoutException: null 

### ISSUE THREAD

**Issue by jobionekabnoi** [spleenware/ripple#45]
I've never really been able to get this issue resolved. I've received this error every time I plug-in a provisioned board. But ripple-messenger will "see" the device I just can't provision it. 

I've used Heltech V2's, TTGO V2 and T-Beams w/ Android 9, 9.1 & 8.1 across multiple devices from a TAB2 to Armor 3WT.  

Below are the debug logs from the 3WT, I'm hoping something jumps out as an issue to someone... I think it's the process as I plug and unplug the otg from the phone. 

`02-04 09:01:49.657  1000   850  1150 D UsbHostManager: USB device attached: vidpid 10c4:ea60 mfg/product/ver/serial Silicon Labs/CP2102 USB to UART Bridge Controller/1.00/0001 hasAudio/HID/Storage: false/false/false
02-04 09:01:49.717  1000   850  1150 D UsbHostManager: Added device UsbDevice[mName=/dev/bus/usb/001/010,mVendorId=4292,mProductId=60000,mClass=0,mSubclass=0,mProtocol=0,mManufacturerName=Silicon Labs,mProductName=CP2102 USB to UART Bridge Controller,mVersion=1.00,mSerialNumber=0001,mConfigurations=[
02-04 09:01:49.717  1000   850  1150 D UsbHostManager: UsbConfiguration[mId=1,mName=null,mAttributes=128,mMaxPower=50,mInterfaces=[
02-04 09:01:49.717  1000   850  1150 D UsbHostManager: UsbInterface[mId=0,mAlternateSetting=0,mName=CP2102 USB to UART Bridge Controller,mClass=255,mSubclass=0,mProtocol=0,mEndpoints=[
02-04 09:01:49.717  1000   850  1150 D UsbHostManager: UsbEndpoint[mAddress=129,mAttributes=2,mMaxPacketSize=64,mInterval=0]
02-04 09:01:49.717  1000   850  1150 D UsbHostManager: UsbEndpoint[mAddress=1,mAttributes=2,mMaxPacketSize=64,mInterval=0]]]]
02-04 09:01:49.735  1000   850  1150 I ActivityManager: START u0 {act=android.hardware.usb.action.USB_DEVICE_ATTACHED flg=0x11000000 cmp=com.spleenware.deviceprovision/.ui.CommanderActivity (has extras)} from uid 1000
02-04 09:01:49.750  1000   850  4133 V WindowManager: Set focused app to: AppWindowToken{e060cbf token=Token{a9502de ActivityRecord{9519219 u0 com.spleenware.deviceprovision/.ui.CommanderActivity t409}}} old focus=AppWindowToken{1992958 token=Token{770be3b ActivityRecord{d35dcca u0 com.android.settings/.SubSettings t408}}} moveFocusNow=true
02-04 09:01:49.750  1000   850  4133 V WindowManager: Changing focus from Window{56fb534 u0 com.android.settings/com.android.settings.SubSettings} to null Callers=com.android.server.wm.WindowManagerService.setFocusedApp:2634 com.android.server.am.ActivityManagerService.setResumedActivityUncheckLocked:3649 com.android.server.am.ActivityStack.onActivityStateChanged:498 com.android.server.am.TaskRecord.onActivityStateChanged:1794 
02-04 09:01:49.751  1000   850  4133 E WindowManager: updateFocusedWindowLocked , Read touchpad force scroll app error! E=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.android.server.wm.WindowState.getOwningPackage()' on a null object reference
02-04 09:01:49.751  1000   850  4133 D WindowManager: Input focus has changed to null
02-04 09:01:49.752  1000   850   922 I WindowManager: Focus moving from Window{56fb534 u0 com.android.settings/com.android.settings.SubSettings} to null
02-04 09:01:49.863  1000   850  2070 I WindowManager: Relayout Window{b5f483e u0 com.spleenware.deviceprovision/com.spleenware.deviceprovision.ui.CommanderActivity}: oldVis=4 newVis=0 focusMayChange = true
02-04 09:01:49.866  1000   850  2070 V WindowManager: Changing focus from null to Window{b5f483e u0 com.spleenware.deviceprovision/com.spleenware.deviceprovision.ui.CommanderActivity} Callers=com.android.server.wm.WindowManagerService.relayoutWindow:2138 com.android.server.wm.Session.relayout:244 android.view.IWindowSession$Stub.onTransact:309 com.android.server.wm.Session.onTransact:164 
02-04 09:01:49.873  1000   850  2070 D WindowManager: Input focus has changed to Window{b5f483e u0 com.spleenware.deviceprovision/com.spleenware.deviceprovision.ui.CommanderActivity}
02-04 09:01:49.874  1000   850   922 I WindowManager: Focus moving from null to Window{b5f483e u0 com.spleenware.deviceprovision/com.spleenware.deviceprovision.ui.CommanderActivity}
02-04 09:01:51.092  1000   850  1150 D UsbHostManager: Removed device at /dev/bus/usb/001/010: CP2102 USB to UART Bridge Controller
02-04 09:01:51.092  1000   850  1150 I UsbAlsaManager: USB Audio Device Removed: null
02-04 09:01:51.095  1000   850  4956 W ActivityManager: Invalid packageName: com.agui.usbcamera
02-04 09:01:51.748  1000   850  2070 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10000000 cmp=com.android.launcher3/com.android.searchlauncher.SearchLauncher (has extras)} from uid 10047
02-04 09:01:51.753  1000   850  2070 W fengjun0525: <0604>ActivityRecord:isHomeIntent, pkg = com.android.launcher3
02-04 09:01:51.762  1000   850  2070 W fengjun0525: ActivityRecord:isHomeIntent, pkg = com.android.launcher3
02-04 09:01:51.776  1000   850  2070 V WindowManager: Set focused app to: AppWindowToken{991fb9a token=Token{3504845 ActivityRecord{d5880bc u0 com.android.launcher3/com.android.searchlauncher.SearchLauncher t2}}} old focus=AppWindowToken{e060cbf token=Token{a9502de ActivityRecord{9519219 u0 com.spleenware.deviceprovision/.ui.CommanderActivity t409}}} moveFocusNow=true
02-04 09:01:51.776  1000   850  2070 V WindowManager: findFocusedWindow: Reached focused app=AppWindowToken{991fb9a token=Token{3504845 ActivityRecord{d5880bc u0 com.android.launcher3/com.android.searchlauncher.SearchLauncher t2}}}
02-04 09:01:51.777  1000   850  2070 V WindowManager: Changing focus from Window{b5f483e u0 com.spleenware.deviceprovision/com.spleenware.deviceprovision.ui.CommanderActivity} to null Callers=com.android.server.wm.WindowManagerService.setFocusedApp:2634 com.android.server.am.ActivityManagerService.setResumedActivityUncheckLocked:3649 com.android.server.am.ActivityStack.onActivityStateChanged:498 com.android.server.am.TaskRecord.onActivityStateChanged:1794 
02-04 09:01:51.777  1000   850  2070 E WindowManager: updateFocusedWindowLocked , Read touchpad force scroll app error! E=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.android.server.wm.WindowState.getOwningPackage()' on a null object reference
02-04 09:01:51.777  1000   850  2070 D WindowManager: Input focus has changed to null
02-04 09:01:51.779  1000   850   922 I WindowManager: Focus moving from Window{b5f483e u0 com.spleenware.deviceprovision/com.spleenware.deviceprovision.ui.CommanderActivity} to null
02-04 09:01:51.791  1000   850  1149 I WindowManager: Relayout Window{87bdb98 u0 com.android.launcher3/com.android.searchlauncher.SearchLauncher}: oldVis=8 newVis=0 focusMayChange = true
02-04 09:01:51.811  1000   850  4721 I WindowManager: Relayout Window{ede4880 u0 com.android.launcher3/com.android.searchlauncher.SearchLauncher}: oldVis=8 newVis=0 focusMayChange = true
02-04 09:01:51.816  1000   850  4721 V WindowManager: Changing focus from null to Window{ede4880 u0 com.android.launcher3/com.android.searchlauncher.SearchLauncher} Callers=com.android.server.wm.WindowManagerService.relayoutWindow:2138 com.android.server.wm.Session.relayout:244 android.view.IWindowSession$Stub.onTransact:309 com.android.server.wm.Session.onTransact:164 
02-04 09:01:51.824  1000   850  4721 D WindowManager: Input focus has changed to Window{ede4880 u0 com.android.launcher3/com.android.searchlauncher.SearchLauncher}
02-04 09:01:51.825  1000   850   922 I WindowManager: Focus moving from null to Window{ede4880 u0 com.android.launcher3/com.android.searchlauncher.SearchLauncher}
02-04 09:01:52.309  1000   850  1150 D UsbHostManager: USB device attached: vidpid 10c4:ea60 mfg/product/ver/serial Silicon Labs/CP2102 USB to UART Bridge Controller/1.00/0001 hasAudio/HID/Storage: false/false/false
02-04 09:01:52.370  1000   850  1150 D UsbHostManager: Added device UsbDevice[mName=/dev/bus/usb/001/011,mVendorId=4292,mProductId=60000,mClass=0,mSubclass=0,mProtocol=0,mManufacturerName=Silicon Labs,mProductName=CP2102 USB to UART Bridge Controller,mVersion=1.00,mSerialNumber=0001,mConfigurations=[
02-04 09:01:52.370  1000   850  1150 D UsbHostManager: UsbConfiguration[mId=1,mName=null,mAttributes=128,mMaxPower=50,mInterfaces=[
02-04 09:01:52.370  1000   850  1150 D UsbHostManager: UsbInterface[mId=0,mAlternateSetting=0,mName=CP2102 USB to UART Bridge Controller,mClass=255,mSubclass=0,mProtocol=0,mEndpoints=[
02-04 09:01:52.370  1000   850  1150 D UsbHostManager: UsbEndpoint[mAddress=129,mAttributes=2,mMaxPacketSize=64,mInterval=0]
02-04 09:01:52.370  1000   850  1150 D UsbHostManager: UsbEndpoint[mAddress=1,mAttributes=2,mMaxPacketSize=64,mInterval=0]]]]
02-04 09:01:52.392  1000   850  1150 I ActivityManager: START u0 {act=android.hardware.usb.action.USB_DEVICE_ATTACHED flg=0x11000000 cmp=com.spleenware.deviceprovision/.ui.CommanderActivity (has extras)} from uid 1000
02-04 09:01:52.400  1000   850  4044 V WindowManager: Set focused app to: AppWindowToken{e060cbf token=Token{a9502de ActivityRecord{9519219 u0 com.spleenware.deviceprovision/.ui.CommanderActivity t409}}} old focus=AppWindowToken{991fb9a token=Token{3504845 ActivityRecord{d5880bc u0 com.android.launcher3/com.android.searchlauncher.SearchLauncher t2}}} moveFocusNow=true
02-04 09:01:52.400  1000   850  4044 V WindowManager: findFocusedWindow: Reached focused app=AppWindowToken{e060cbf token=Token{a9502de ActivityRecord{9519219 u0 com.spleenware.deviceprovision/.ui.CommanderActivity t409}}}
02-04 09:01:52.401  1000   850  4044 V WindowManager: Changing focus from Window{ede4880 u0 com.android.launcher3/com.android.searchlauncher.SearchLauncher} to null Callers=com.android.server.wm.WindowManagerService.setFocusedApp:2634 com.android.server.am.ActivityManagerService.setResumedActivityUncheckLocked:3649 com.android.server.am.ActivityStack.onActivityStateChanged:498 com.android.server.am.TaskRecord.onActivityStateChanged:1794 
02-04 09:01:52.401  1000   850  4044 E WindowManager: updateFocusedWindowLocked , Read touchpad force scroll app error! E=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.android.server.wm.WindowState.getOwningPackage()' on a null object reference
02-04 09:01:52.401  1000   850  4044 D WindowManager: Input focus has changed to null
02-04 09:01:52.404  1000   850   922 I WindowManager: Focus moving from Window{ede4880 u0 com.android.launcher3/com.android.searchlauncher.SearchLauncher} to null
02-04 09:01:53.109  1000   850   908 W ActivityManager: Activity pause timeout for ActivityRecord{9519219 u0 com.spleenware.deviceprovision/.ui.CommanderActivity t409}
02-04 09:01:53.110  1000   850   908 V WindowManager: Set focused app to: AppWindowToken{1992958 token=Token{770be3b ActivityRecord{d35dcca u0 com.android.settings/.SubSettings t408}}} old focus=AppWindowToken{e060cbf token=Token{a9502de ActivityRecord{9519219 u0 com.spleenware.deviceprovision/.ui.CommanderActivity t409}}} moveFocusNow=true
02-04 09:01:53.127  1000   850   913 E BatteryExternalStatsWorker: no controller energy info supplied for wifi
02-04 09:01:53.166  1000   850  4721 I ProcessStatsService: Added stats: 2022-02-03-22-50-27, over +5s265ms
02-04 09:01:53.174  1000   850  4721 I ProcessStatsService: Added stats: 2022-02-03-19-33-15, over +6s69ms
02-04 09:01:53.174  1000   850  2070 I WindowManager: Relayout Window{56fb534 u0 com.android.settings/com.android.settings.SubSettings}: oldVis=4 newVis=0 focusMayChange = true
02-04 09:01:53.177  1000   850  2070 V WindowManager: Changing focus from null to Window{56fb534 u0 com.android.settings/com.android.settings.SubSettings} Callers=com.android.server.wm.WindowManagerService.relayoutWindow:2138 com.android.server.wm.Session.relayout:244 android.view.IWindowSession$Stub.onTransact:309 com.android.server.wm.Session.onTransact:164 
02-04 09:01:53.181  1000   850  4721 I ProcessStatsService: Added stats: 2022-02-03-19-26-16, over +7s531ms
02-04 09:01:53.183  1000   850  2070 D WindowManager: Input focus has changed to Window{56fb534 u0 com.android.settings/com.android.settings.SubSettings}
02-04 09:01:53.184  1000   850   922 I WindowManager: Focus moving from null to Window{56fb534 u0 com.android.settings/com.android.settings.SubSettings}
02-04 09:01:53.188  1000   850  4721 I ProcessStatsService: Added stats: 2022-01-22-16-50-43, over +8m34s158ms
02-04 09:01:53.195  1000   850  4721 I ProcessStatsService: Added stats: 2022-01-22-13-50-42, over +3h0m0s883ms
02-04 09:01:53.225  1000   850   933 V SettingsProvider: name : screen_brightness appId : 1000
02-04 09:01:53.345  1000   850  4721 I ActivityManager: START u0 {act=android.intent.action.MAIN cmp=com.android.settings/.SubSettings (has extras)} from uid 1000
02-04 09:01:53.355  1000   850  2070 V WindowManager: Set focused app to: AppWindowToken{b359d7b token=Token{811b10a ActivityRecord{530ad75 u0 com.android.settings/.SubSettings t408}}} old focus=AppWindowToken{1992958 token=Token{770be3b ActivityRecord{d35dcca u0 com.android.settings/.SubSettings t408}}} moveFocusNow=true
02-04 09:01:53.355  1000   850  2070 V WindowManager: Changing focus from Window{56fb534 u0 com.android.settings/com.android.settings.SubSettings} to null Callers=com.android.server.wm.WindowManagerService.setFocusedApp:2634 com.android.server.am.ActivityManagerService.setResumedActivityUncheckLocked:3649 com.android.server.am.ActivityStack.onActivityStateChanged:498 com.android.server.am.TaskRecord.onActivityStateChanged:1794 
02-04 09:01:53.356  1000   850  2070 E WindowManager: updateFocusedWindowLocked , Read touchpad force scroll app error! E=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.android.server.wm.WindowState.getOwningPackage()' on a null object reference
02-04 09:01:53.356  1000   850  2070 D WindowManager: Input focus has changed to null
02-04 09:01:53.356  1000   850   922 I WindowManager: Focus moving from Window{56fb534 u0 com.android.settings/com.android.settings.SubSettings} to null
02-04 09:01:53.403  1000   850   850 W Looper  : Slow dispatch took 1030ms main h=android.app.ActivityThread$H c=android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA@b6babf1 m=0
02-04 09:01:53.403  1000   850   850 W Looper  : Slow delivery took 1019ms main h=com.android.server.job.JobSchedulerService$JobHandler c=null m=4
02-04 09:01:53.404  1000   850   850 V SettingsProvider: Notifying for 0: content://settings/system/screen_brightness
02-04 09:01:53.404  1000   850   933 V SettingsProvider: name : screen_brightness appId : 1000
02-04 09:01:53.419  1000   850  1920 I WindowManager: Relayout Window{ed2e829 u0 com.android.settings/com.android.settings.SubSettings}: oldVis=4 newVis=0 focusMayChange = true
02-04 09:01:53.420  1000   850   850 W Looper  : Drained
02-04 09:01:53.422  1000   850  1920 V WindowManager: Changing focus from null to Window{ed2e829 u0 com.android.settings/com.android.settings.SubSettings} Callers=com.android.server.wm.WindowManagerService.relayoutWindow:2138 com.android.server.wm.Session.relayout:244 android.view.IWindowSession$Stub.onTransact:309 com.android.server.wm.Session.onTransact:164 
02-04 09:01:53.428  1000   850  1920 D WindowManager: Input focus has changed to Window{ed2e829 u0 com.android.settings/com.android.settings.SubSettings}
02-04 09:01:53.428  1000   850   922 I WindowManager: Focus moving from null to Window{ed2e829 u0 com.android.settings/com.android.settings.SubSettings}
02-04 09:01:54.195  1000   850   933 V SettingsProvider: name : screen_brightness appId : 1000
02-04 09:01:54.403  1000   850  1150 D UsbHostManager: Removed device at /dev/bus/usb/001/011: CP2102 USB to UART Bridge Controller
02-04 09:01:54.404  1000   850  1150 I UsbAlsaManager: USB Audio Device Removed: null
02-04 09:01:54.410  1000   850  1149 W ActivityManager: Invalid packageName: com.agui.usbcamera
02-04 09:01:54.437  1000   850  1920 I WindowManager: Relayout Window{b5f483e u0 com.spleenware.deviceprovision/com.spleenware.deviceprovision.ui.CommanderActivity}: oldVis=4 newVis=0 focusMayChange = true
02-04 09:01:57.037  1000   850  4721 V WindowManager: Set focused app to: AppWindowToken{1992958 token=Token{770be3b ActivityRecord{d35dcca u0 com.android.settings/.SubSettings t408}}} old focus=AppWindowToken{b359d7b token=Token{811b10a ActivityRecord{530ad75 u0 com.android.settings/.SubSettings t408}}} moveFocusNow=true
02-04 09:01:57.038  1000   850  4721 V WindowManager: Changing focus from Window{ed2e829 u0 com.android.settings/com.android.settings.SubSettings} to null Callers=com.android.server.wm.WindowManagerService.setFocusedApp:2634 com.android.server.am.ActivityManagerService.setResumedActivityUncheckLocked:3649 com.android.server.am.ActivityStack.onActivityStateChanged:498 com.android.server.am.TaskRecord.onActivityStateChanged:1794 
02-04 09:01:57.039  1000   850  4721 E WindowManager: updateFocusedWindowLocked , Read touchpad force scroll app error! E=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.android.server.wm.WindowState.getOwningPackage()' on a null object reference
02-04 09:01:57.040  1000   850  4721 D WindowManager: Input focus has changed to null
02-04 09:01:57.046  1000   850   922 I WindowManager: Focus moving from Window{ed2e829 u0 com.android.settings/com.android.settings.SubSettings} to null
02-04 09:01:57.074  1000   850   913 E BatteryExternalStatsWorker: no controller energy info supplied for wifi
02-04 09:01:57.124  1000   850  2070 I ProcessStatsService: Added stats: 2022-02-03-22-50-27, over +5s265ms
02-04 09:01:57.132  1000   850  2070 I ProcessStatsService: Added stats: 2022-02-03-19-33-15, over +6s69ms
02-04 09:01:57.138  1000   850  4133 I WindowManager: Relayout Window{56fb534 u0 com.android.settings/com.android.settings.SubSettings}: oldVis=4 newVis=0 focusMayChange = true
02-04 09:01:57.140  1000   850  2070 I ProcessStatsService: Added stats: 2022-02-03-19-26-16, over +7s531ms
02-04 09:01:57.142  1000   850  4133 V WindowManager: Changing focus from null to Window{56fb534 u0 com.android.settings/com.android.settings.SubSettings} Callers=com.android.server.wm.WindowManagerService.relayoutWindow:2138 com.android.server.wm.Session.relayout:244 android.view.IWindowSession$Stub.onTransact:309 com.android.server.wm.Session.onTransact:164 
02-04 09:01:57.148  1000   850  4133 D WindowManager: Input focus has changed to Window{56fb534 u0 com.android.settings/com.android.settings.SubSettings}
02-04 09:01:57.148  1000   850  2070 I ProcessStatsService: Added stats: 2022-01-22-16-50-43, over +8m34s158ms
02-04 09:01:57.150  1000   850   922 I WindowManager: Focus moving from null to Window{56fb534 u0 com.android.settings/com.android.settings.SubSettings}
02-04 09:01:57.156  1000   850  2070 I ProcessStatsService: Added stats: 2022-01-22-13-50-42, over +3h0m0s883ms
02-04 09:01:57.692  1000   850  1150 D UsbHostManager: USB device attached: vidpid 10c4:ea60 mfg/product/ver/serial Silicon Labs/CP2102 USB to UART Bridge Controller/1.00/0001 hasAudio/HID/Storage: false/false/false
02-04 09:01:57.753  1000   850  1150 D UsbHostManager: Added device UsbDevice[mName=/dev/bus/usb/001/014,mVendorId=4292,mProductId=60000,mClass=0,mSubclass=0,mProtocol=0,mManufacturerName=Silicon Labs,mProductName=CP2102 USB to UART Bridge Controller,mVersion=1.00,mSerialNumber=0001,mConfigurations=[
02-04 09:01:57.753  1000   850  1150 D UsbHostManager: UsbConfiguration[mId=1,mName=null,mAttributes=128,mMaxPower=50,mInterfaces=[
02-04 09:01:57.753  1000   850  1150 D UsbHostManager: UsbInterface[mId=0,mAlternateSetting=0,mName=CP2102 USB to UART Bridge Controller,mClass=255,mSubclass=0,mProtocol=0,mEndpoints=[
02-04 09:01:57.753  1000   850  1150 D UsbHostManager: UsbEndpoint[mAddress=129,mAttributes=2,mMaxPacketSize=64,mInterval=0]
02-04 09:01:57.753  1000   850  1150 D UsbHostManager: UsbEndpoint[mAddress=1,mAttributes=2,mMaxPacketSize=64,mInterval=0]]]]
02-04 09:01:57.792  1000   850  1150 I ActivityManager: START u0 {act=android.hardware.usb.action.USB_DEVICE_ATTACHED flg=0x11000000 cmp=com.spleenware.deviceprovision/.ui.CommanderActivity (has extras)} from uid 1000
02-04 09:01:57.801  1000   850  4133 V WindowManager: Set focused app to: AppWindowToken{e060cbf token=Token{a9502de ActivityRecord{9519219 u0 com.spleenware.deviceprovision/.ui.CommanderActivity t409}}} old focus=AppWindowToken{1992958 token=Token{770be3b ActivityRecord{d35dcca u0 com.android.settings/.SubSettings t408}}} moveFocusNow=true
02-04 09:01:57.801  1000   850  4133 V WindowManager: findFocusedWindow: Reached focused app=AppWindowToken{e060cbf token=Token{a9502de ActivityRecord{9519219 u0 com.spleenware.deviceprovision/.ui.CommanderActivity t409}}}
02-04 09:01:57.801  1000   850  4133 V WindowManager: Changing focus from Window{56fb534 u0 com.android.settings/com.android.settings.SubSettings} to null Callers=com.android.server.wm.WindowManagerService.setFocusedApp:2634 com.android.server.am.ActivityManagerService.setResumedActivityUncheckLocked:3649 com.android.server.am.ActivityStack.onActivityStateChanged:498 com.android.server.am.TaskRecord.onActivityStateChanged:1794 
02-04 09:01:57.802  1000   850  4133 E WindowManager: updateFocusedWindowLocked , Read touchpad force scroll app error! E=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.android.server.wm.WindowState.getOwningPackage()' on a null object reference
02-04 09:01:57.802  1000   850  4133 D WindowManager: Input focus has changed to null
02-04 09:01:57.804  1000   850   922 I WindowManager: Focus moving from Window{56fb534 u0 com.android.settings/com.android.settings.SubSettings} to null
02-04 09:01:57.839  1000   850  4133 I WindowManager: Relayout Window{b5f483e u0 com.spleenware.deviceprovision/com.spleenware.deviceprovision.ui.CommanderActivity}: oldVis=4 newVis=0 focusMayChange = true
02-04 09:01:57.842  1000   850  4133 V WindowManager: Changing focus from null to Window{b5f483e u0 com.spleenware.deviceprovision/com.spleenware.deviceprovision.ui.CommanderActivity} Callers=com.android.server.wm.WindowManagerService.relayoutWindow:2138 com.android.server.wm.Session.relayout:244 android.view.IWindowSession$Stub.onTransact:309 com.android.server.wm.Session.onTransact:164 
02-04 09:01:57.848  1000   850  4133 D WindowManager: Input focus has changed to Window{b5f483e u0 com.spleenware.deviceprovision/com.spleenware.deviceprovision.ui.CommanderActivity}
02-04 09:01:57.848  1000   850   922 I WindowManager: Focus moving from null to Window{b5f483e u0 com.spleenware.deviceprovision/com.spleenware.deviceprovision.ui.CommanderActivity}
02-04 09:01:59.626  1000   850   933 V SettingsProvider: name : screen_brightness appId : 1000
02-04 09:01:59.627  1000   850   850 V SettingsProvider: Notifying for 0: content://settings/system/screen_brightness
02-04 09:01:59.628  1000   850   933 V SettingsProvider: name : screen_brightness appId : 1000`

**Comment by spleenware** [comment]
I believe this is now fixed in the latest version of Commander.
