### ISSUE TITLE
Which code to use to flash

### ISSUE THREAD

**Issue by 17dshaikh** [spleenware/ripple#52]
Hi I am wishing to create the gps lora tracker but I am confused I don't know which code to use to flash the gps lora boardand what code to flash the board for the commander app please help.
I am using the adafruit lora board 433mhz
Thanks

**Comment by spleenware** [comment]
I'm assuming you're using two Feathers, one for the tracker, one for the 'home' radio (connects to Android and the Commander app).
For the 'home' radio, flash this: https://github.com/spleenware/ripple/blob/master/RippleV5-USB-feather.bin
For the tracker, flash this: https://github.com/spleenware/ripple/blob/master/RippleTrackerV5-Feather.bin

**Comment by 17dshaikh** [comment]
Should I use arduino ide to flash it or something else?

**Comment by 17dshaikh** [comment]
Sorry pressed wrong button

**Comment by 17dshaikh** [comment]
As the guide mentions a flasher but also ardunio ide

**Comment by spleenware** [comment]
The EspHome flasher tool is by far the easiest way

**Comment by 17dshaikh** [comment]
Do you have a link for the download of that program

**Comment by spleenware** [comment]
https://github.com/esphome/esphome-flasher/releases
