### ISSUE TITLE
Flashing not working

### ISSUE THREAD

**Issue by 17dshaikh** [spleenware/ripple#54]
when i flash it it says Using 'COM6' as serial port.
Unexpected error: could not open port 'COM6': PermissionError(13, 'Access is denied.', None, 5)

**Comment by 17dshaikh** [comment]
And which libaries to use for the arduino flashing for the gps tracker adn commander feather as well

**Comment by 17dshaikh** [comment]
sorry wrong button

**Comment by 17dshaikh** [comment]
And does it matter that i used spring antennas instead of the dipole one

**Comment by spleenware** [comment]
No.  The dipole is just more sensitive, can get better range
