### ISSUE TITLE
Home base station with computer

### ISSUE THREAD

**Issue by LuxStatera** [spleenware/ripple#59]
I see that Ripple works with Android and the standalone messengers but is there also an option to connect the ESP device to a computer or Pi with a USB cable? I'd like to build a home base station that can send/receive messages and also act as a repeater/mailbox

**Comment by spleenware** [comment]
You could run a Pi or similar and write your own client/UI but just talking the serial protocol over USB to a standard Ripple node (eg. on a Heltec or TTGO, for instance), but make sure you pick the USB-OTG firmware for the device.
Then you can follow the sample code in the 'Custom Node Programming' guide here:
   https://github.com/spleenware/ripple/wiki/Custom-Node-Programming
And write similar in whatever language on the Pi or laptop.
