### ISSUE TITLE
Repeaters

### ISSUE THREAD

**Issue by 17dshaikh** [spleenware/ripple#60]
Hi , I have found that the Helltec boards are now discontinued and ttgo ones are hard to source, would it be possible to use the Adafruit Lora boards to create a repeater for the LoRa network to increase range of the network
Thanks

**Comment by spleenware** [comment]
I have just uploaded a Repeater firmware for the Feather. The 'post office' feature is not available for this build, however. (no SPIFFFS file system on the feather, sadly)
https://github.com/spleenware/ripple/blob/master/RippleRepeater-Feather.bin
