### ISSUE TITLE
sharing the code for working with CARDKB on a regular ESP32

### ISSUE THREAD

**Issue by richonguzman** [spleenware/ripple#62]
Hi!

could you share the code for working with CARDKB on a regular ESP32???

**Comment by spleenware** [comment]
It's  pretty simple. You just use the I2C 'Wire' library:

#include <Wire.h>
#define CARDKB_ADDR 0x5F

  Wire.requestFrom(CARDKB_ADDR, 1);
  if (Wire.available()) {
    char c = Wire.read();
    // process the key press
  }

**Comment by spleenware** [comment]
I don't think that is applicable for the CardKb, ie. you just get whole press events, (a down then up, combined).

**Comment by richonguzman** [comment]
Thanks a Lot for this info, got my CardKB working with the T-Beam Lora32 V.1 and its working awesome.

did a menu and all to mimic APRS VHF over LoRa ;)
