### ISSUE TITLE
 The Ripple program (Android 8.0.0 and Android 5) terminates with an error

### ISSUE THREAD

**Issue by luxonn** [spleenware/ripple#9]
The Ripple program (Android 8.0.0 and Android 5) terminates with an error when receiving geo coordinates. Unfortunately I can not use the old tablet and phone with version 4 of android. 
Firmware: Ripple-433-Bluetooth.heltec_v2.bin

**Comment by spleenware** [comment]
Hi, OK I have a crash report for that now from Play. I'll get a fix out for that this weekend.

**Comment by luxonn** [comment]
When more than More than two pagers, one of the three is not in communication. I still don’t understand if relaying works. Do pagers form a network? 
Which means: "Unable to update friends: TimeoutException: null" Such a message often happens, especially when there are three pagers.

**Comment by spleenware** [comment]
> When more than More than two pagers, one of the three is not in communication. I still don’t understand if relaying works. Do pagers form a network?
> Which means: "Unable to update friends: TimeoutException: null" Such a message often happens, especially when there are three pagers.

I'm still not sure what causes that error, but I have only reproduced it a couple of times. Most the time, simply unplugging the USB cable, and plugging in again clears everything up.

Are you using one of the Bluetooth builds, or USB OTG?

**Comment by spleenware** [comment]
OK, I have published ver 1.2.1 of the Ripple Messenger app on Google Play. It should contain the geo location bug fix.

**Comment by luxonn** [comment]
I use only bluetooth. It is convenient and not all have the OTG cables

сб, 21 дек. 2019 г., 11:42 spleenware <notifications@github.com>:
